import { StyleSheet } from 'react-native';
export const radarScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#020617' },
  
  // Header
  mainHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 20 },
  appName: { color: '#F8FAFC', fontSize: 22, fontWeight: '900', letterSpacing: 1 },
  headerRight: { flexDirection: 'row', gap: 10 },
  iconBtn: { padding: 10, backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 12, justifyContent: 'center', alignItems: 'center' },

  // Hero
  heroCard: { marginHorizontal: 16, marginTop: 6, marginBottom: 8, borderRadius: 22, overflow: 'hidden', paddingHorizontal: 12, paddingVertical: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)', backgroundColor: 'rgba(12,18,32,0.92)' },
  heroGlowPrimary: { position: 'absolute', width: 180, height: 180, borderRadius: 90, backgroundColor: 'rgba(78,205,196,0.18)', top: -40, right: -24 },
  heroGlowSecondary: { position: 'absolute', width: 160, height: 160, borderRadius: 80, backgroundColor: 'rgba(255,82,82,0.08)', bottom: -50, left: -24 },
  heroTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  heroEyebrow: { color: '#38BDF8', fontSize: 12, letterSpacing: 1, fontWeight: '700', textTransform: 'uppercase' },
  heroTitle: { color: '#F8FAFC', fontSize: 22, fontWeight: '900', letterSpacing: 0.4, marginTop: 2 },
  heroBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#4ECDC4', paddingHorizontal: 11, paddingVertical: 7, borderRadius: 14, gap: 6, shadowColor: '#4ECDC4', shadowOpacity: 0.4, shadowRadius: 10, elevation: 4 },
  heroBadgeText: { color: '#0B1424', fontWeight: '900', letterSpacing: 0.5 },
  radarShell: { alignItems: 'center', justifyContent: 'center', marginTop: -8, marginBottom: 0 },
  radarAura: { position: 'absolute', backgroundColor: 'rgba(78,205,196,0.05)' },
  radarChip: { position: 'absolute', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 7, borderRadius: 14, backgroundColor: 'rgba(2,6,23,0.82)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
  radarChipLeft: { top: 12, left: 14 },
  radarChipRight: { top: 12, right: 14 },
  radarChipText: { color: '#E2E8F0', marginLeft: 6, fontWeight: '600', fontSize: 12 },
  statRow: { flexDirection: 'row', gap: 8, marginTop: 2 },
  statCard: { flex: 1, padding: 8, borderRadius: 12, borderWidth: 1, backgroundColor: 'rgba(255,255,255,0.03)' },
  statIcon: { width: 28, height: 28, borderRadius: 9, alignItems: 'center', justifyContent: 'center', marginBottom: 5 },
  statLabel: { color: '#94A3B8', fontSize: 11, letterSpacing: 0.4 },
  statValue: { color: '#F8FAFC', fontWeight: '800', fontSize: 15 },
  statHint: { color: '#94A3B8', fontSize: 10, marginTop: 3, fontWeight: '600' },
  startButton: { marginTop: 6, borderRadius: 18, overflow: 'hidden', shadowColor: '#FF5252', shadowRadius: 16, shadowOpacity: 0.45, shadowOffset: { width: 0, height: 8 }, elevation: 8 },
  startButtonGradient: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 18 },
  startText: { color: '#FFFFFF', fontWeight: '900', fontSize: 17, letterSpacing: 0.5 },
  startSubtext: { color: '#F8FAFC', opacity: 0.8, fontSize: 12, marginTop: 4 },
  startBadge: { width: 42, height: 42, borderRadius: 12, backgroundColor: '#F8FAFC', alignItems: 'center', justifyContent: 'center' },
  homeQuickPanel: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.2)',
    backgroundColor: 'rgba(7,14,28,0.82)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: 'space-between',
    gap: 10,
  },
  homeQuickRow: {
    flexDirection: 'row',
    gap: 8,
  },
  homeQuickButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.25)',
    backgroundColor: 'rgba(15,23,42,0.72)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    gap: 8,
  },
  homeQuickButtonPrimary: {
    borderColor: 'rgba(78,205,196,0.45)',
  },
  homeQuickButtonText: {
    color: '#E2E8F0',
    fontWeight: '700',
    fontSize: 12,
  },
  homeQuickMeta: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
  },

  // Hero Actions & Voice Pill
  heroActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  voicePill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 14, gap: 5 },
  voicePillOn: { backgroundColor: '#4ECDC4' },
  voicePillOff: { backgroundColor: 'rgba(255,255,255,0.08)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)' },
  voicePillText: { fontSize: 12, fontWeight: '700' },
  voicePillTextOn: { color: '#0B1424' },
  voicePillTextOff: { color: '#E2E8F0' },

  // Pro Slider
  sliderContainer: { marginHorizontal: 16, marginTop: 0, marginBottom: 10, borderRadius: 18, overflow: 'hidden' },
  sliderGradient: { paddingVertical: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
  proIconBox: { width: 32, height: 32, borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  pager: { flexDirection: 'row', justifyContent: 'center', marginTop: 15, gap: 6 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#334155' },

  // Driving Mode
  drivingHeader: { paddingBottom: 10, paddingHorizontal: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#000' },
  drivingModeTitle: { color: 'white', fontWeight: '900', fontSize: 16 },
  drivingModeSub: { color: '#4ECDC4', fontSize: 10, fontWeight: 'bold', letterSpacing: 1 },
  tabBar: { flexDirection: 'row', justifyContent: 'center', backgroundColor: '#111', marginHorizontal: 20, borderRadius: 12, padding: 4, marginBottom: 10 },
  tabItem: { paddingVertical: 8, paddingHorizontal: 20, borderRadius: 8 },
  activeTabItem: { backgroundColor: '#222' },
  tabText: { color: '#888', fontWeight: 'bold', fontSize: 12 },

  liveAlertBanner: {
    marginHorizontal: 20,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: 'rgba(255,82,82,0.35)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  liveAlertIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: 'rgba(255,82,82,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveAlertTitle: { color: 'white', fontWeight: '700', fontSize: 13 },
  liveAlertSubtitle: { color: '#94A3B8', fontSize: 11, marginTop: 2 },
  liveAlertDismiss: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(148,163,184,0.1)',
  },
  
  // Navigation Progress Styles
  navigationProgress: {
    marginHorizontal: 20,
    marginBottom: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: 'rgba(78,205,196,0.35)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  progressIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: 'rgba(78,205,196,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressTitle: { color: 'white', fontWeight: '700', fontSize: 13 },
  progressSubtitle: { color: '#94A3B8', fontSize: 11, marginTop: 2, flex: 1 },
  progressDistance: { alignItems: 'center', justifyContent: 'center' },
  progressDistanceText: { color: '#4ECDC4', fontWeight: 'bold', fontSize: 12 },
  arrivedEndTripButton: {
    backgroundColor: '#4ECDC4',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  arrivedEndTripText: {
    color: '#0B1424',
    fontWeight: '800',
    fontSize: 12,
  },
  
  basicScroll: { flex: 1 },
  basicContainer: { alignItems: 'center', paddingTop: 20 },
  basicTopAdContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 14,
    paddingHorizontal: 12,
  },
  basicBottomAdContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 8,
    paddingHorizontal: 12,
  },
  hudCircle: { width: 220, height: 220, borderRadius: 110, justifyContent: 'center', alignItems: 'center', borderWidth: 4, borderColor: '#222', backgroundColor: '#111' },
  ring: { position: 'absolute', width: 200, height: 200, borderRadius: 100, borderWidth: 4, borderColor: '#333' },
  speedText: { color: 'white', fontSize: 72, fontWeight: '900' },
  unitText: { color: '#666', fontSize: 16, fontWeight: 'bold', marginTop: -5 },
  
  alertsList: { width: '100%', padding: 20, marginTop: 20 },
  sectionHeader: { color: '#64748B', fontSize: 12, fontWeight: 'bold', marginBottom: 15, letterSpacing: 1 },
  alertItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.05)', padding: 15, borderRadius: 16, marginBottom: 10 },
  alertText: { color: 'white', flex: 1, marginLeft: 15, fontWeight: '500' },
  alertDist: { color: '#FFD700', fontWeight: 'bold' },

  // Map
  mapOverlay: { position: 'absolute', top: 20, left: 20, right: 20 },
  mapInput: { backgroundColor: 'rgba(0,0,0,0.8)', padding: 15, borderRadius: 16, color: 'white' },
  mapControls: { position: 'absolute', alignItems: 'center', zIndex: 10 },
  mapLeftControls: { position: 'absolute', alignItems: 'center', zIndex: 10 },
  mapControlButton: { borderRadius: 16, backgroundColor: 'rgba(15,23,42,0.95)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', alignItems: 'center', justifyContent: 'center' },
  mapControlButtonActive: { backgroundColor: '#4ECDC4', borderColor: '#4ECDC4' },
  mapIncidentButton: {
    backgroundColor: 'rgba(255,82,82,0.9)',
    borderColor: 'rgba(255,82,82,0.95)',
  },
  mapAdContainer: { position: 'absolute', alignItems: 'center' },
  homeAdContainer: {
    marginHorizontal: 16,
    marginBottom: 10,
    alignItems: 'center',
  },

  navTopCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 18,
    backgroundColor: 'rgba(7,14,28,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(56,189,248,0.28)',
  },
  navTopIconShell: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: 'rgba(148,163,184,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navTopCopy: { flex: 1 },
  navTopDistance: {
    color: '#F8FAFC',
    fontSize: 16,
    fontWeight: '800',
  },
  navTopInstruction: {
    color: '#CBD5E1',
    fontSize: 12,
    marginTop: 2,
  },
  navTopClose: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(30,41,59,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.26)',
  },
  navTopActionPrimary: {
    backgroundColor: '#4ECDC4',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  navTopActionPrimaryText: {
    color: '#06212B',
    fontWeight: '800',
    fontSize: 13,
  },

  navSummaryCard: {
    backgroundColor: 'rgba(3,10,24,0.95)',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(56,189,248,0.3)',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  navSummaryDistance: {
    color: '#F8FAFC',
    fontSize: 26,
    fontWeight: '900',
  },
  navSummaryEta: {
    color: '#67E8F9',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 2,
  },
  navSummaryDestination: {
    color: '#94A3B8',
    fontSize: 12,
    marginTop: 4,
  },

  navCompactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: 'rgba(9,15,28,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(78,205,196,0.25)',
  },
  navCompactInfo: { flex: 1 },
  navCompactTitle: { color: '#F8FAFC', fontWeight: '800', fontSize: 14 },
  navCompactMeta: { color: '#94A3B8', marginTop: 2, fontSize: 11 },
  navCompactButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  navCompactButtonDanger: {
    backgroundColor: 'rgba(255,82,82,0.9)',
    borderColor: 'rgba(255,82,82,0.9)',
  },

  fab: { position: 'absolute', left: 20, backgroundColor: '#FF5252', width: 56, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', elevation: 10, shadowColor: '#000', shadowOffset: {width:0, height:4}, shadowOpacity:0.3, shadowRadius:4 },
  reportSheet: { backgroundColor: '#1E293B', padding: 30, borderTopLeftRadius: 30, borderTopRightRadius: 30 },
  sheetTitle: { color: 'white', fontSize: 20, fontWeight: 'bold', textAlign: 'center' },
  reportIconBig: { width: 70, height: 70, borderRadius: 35, justifyContent: 'center', alignItems: 'center' },

  suggestionsContainer: { backgroundColor: '#0F172A', borderRadius: 12, marginTop: 6, paddingVertical: 5, maxHeight: 220, borderWidth: 1, borderColor: 'rgba(148,163,184,0.2)', zIndex: 20, elevation: 8 },
  suggestionItem: { flexDirection: 'row', alignItems: 'center', padding: 12, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  suggestionText: { color: '#F8FAFC', marginLeft: 10, flex: 1 },
  
  bottomNavDock: { position: 'absolute', zIndex: 11 },
  navInstructionBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#0B1220', padding: 12, borderRadius: 14, marginTop: 8, borderWidth: 1, borderColor: 'rgba(78,205,196,0.35)' },
  navInstructionDock: { marginTop: 0, backgroundColor: 'rgba(11,18,32,0.96)' },
});
