export type ExternalCameraSourceRule = {
  key: string;
  label: string;
  provider: 'osm' | 'lufop' | 'government_open_data' | 'community';
  region: string;
  countryCodes: string[];
  status: 'active' | 'draft' | 'planned';
  ingestMode: 'api' | 'feed' | 'scrape' | 'manual';
  alertPolicy?: 'driver_alert' | 'map_only' | 'ignore';
  endpointUrl?: string;
  updateCadence?: string;
  cameraTypes: string[];
  notes: string;
  matchingHints: string[];
};

// Global ingestion scaffold aligned to Trafik_Kameralari_Kilavuzu.pdf.
// Keep source-specific auth, parsers, and legal filters outside this file.
export const EXTERNAL_CAMERA_SOURCE_RULES: ExternalCameraSourceRule[] = [
  {
    key: 'osm',
    label: 'OpenStreetMap Cameras',
    provider: 'osm',
    region: 'Global',
    countryCodes: ['*'],
    status: 'active',
    ingestMode: 'feed',
    alertPolicy: 'driver_alert',
    endpointUrl: 'https://overpass-api.de/api/interpreter',
    updateCadence: 'community-updated',
    cameraTypes: ['speed_fixed', 'red_light', 'traffic_light'],
    notes: 'Global baseline feed for fixed enforcement points and openly mapped camera nodes.',
    matchingHints: ['highway=speed_camera', 'enforcement=maxspeed', 'camera:type=speed'],
  },
  {
    key: 'lufop',
    label: 'Lufop Europe API',
    provider: 'lufop',
    region: 'Europe',
    countryCodes: [
      'FR', 'GB', 'BE', 'NL', 'DE', 'ES', 'IT', 'PT',
      'CH', 'AT', 'PL', 'CZ', 'SE', 'NO', 'DK', 'FI',
    ],
    status: 'draft',
    ingestMode: 'api',
    alertPolicy: 'driver_alert',
    endpointUrl: 'https://lufop.net/en/lufop-api',
    updateCadence: 'monthly-validated',
    cameraTypes: ['speed_fixed', 'speed_mobile', 'red_light', 'speed_average', 'construction'],
    notes: 'Primary Europe-specific enrichment source described in the traffic camera guide.',
    matchingHints: ['fixed', 'mobile', 'redlight', 'average', 'construction'],
  },
  {
    key: 'gov_us_data',
    label: 'US Government Open Data',
    provider: 'government_open_data',
    region: 'United States',
    countryCodes: ['US'],
    status: 'draft',
    ingestMode: 'scrape',
    alertPolicy: 'ignore',
    endpointUrl: 'https://catalog.data.gov/dataset',
    updateCadence: 'source-dependent',
    cameraTypes: ['speed_fixed', 'red_light', 'traffic_light'],
    notes: 'Use as a discovery layer for federal, state, county, and city traffic camera datasets.',
    matchingHints: ['data-gov', 'traffic camera', 'speed camera', 'open data'],
  },
  {
    key: 'gov_au_act',
    label: 'ACT Open Data',
    provider: 'government_open_data',
    region: 'Australia',
    countryCodes: ['AU'],
    status: 'draft',
    ingestMode: 'api',
    alertPolicy: 'driver_alert',
    endpointUrl: 'https://www.data.act.gov.au/',
    updateCadence: 'source-dependent',
    cameraTypes: ['speed_fixed', 'speed_mobile', 'red_light'],
    notes: 'Australian camera/open road safety datasets start here; extend by state feed adapters.',
    matchingHints: ['data.act.gov.au', 'speed camera', 'road safety'],
  },
  {
    key: 'gov_ca_open',
    label: 'Canada Open Government',
    provider: 'government_open_data',
    region: 'Canada',
    countryCodes: ['CA'],
    status: 'planned',
    ingestMode: 'scrape',
    alertPolicy: 'ignore',
    endpointUrl: 'https://open.canada.ca/data/en/dataset',
    updateCadence: 'source-dependent',
    cameraTypes: ['speed_fixed', 'traffic_light'],
    notes: 'National discovery layer; likely requires province/city adapter completion.',
    matchingHints: ['open.canada.ca', 'traffic camera', 'open government'],
  },
  {
    key: 'gov_uk_data',
    label: 'UK Government Open Data',
    provider: 'government_open_data',
    region: 'United Kingdom',
    countryCodes: ['GB'],
    status: 'planned',
    ingestMode: 'scrape',
    alertPolicy: 'ignore',
    endpointUrl: 'https://data.gov.uk/',
    updateCadence: 'source-dependent',
    cameraTypes: ['speed_fixed', 'red_light', 'speed_average'],
    notes: 'Use as the UK official dataset discovery layer; local authority feeds must be normalized.',
    matchingHints: ['data.gov.uk', 'speed camera', 'average speed', 'road safety'],
  },
  {
    key: 'gov_dc_speed_detector',
    label: 'DC Speed Detector Locations',
    provider: 'government_open_data',
    region: 'Washington, DC',
    countryCodes: ['US'],
    status: 'active',
    ingestMode: 'api',
    alertPolicy: 'driver_alert',
    endpointUrl:
      'https://maps2.dcgis.dc.gov/dcgis/rest/services/DCGIS_DATA/Transportation_WebMercator/MapServer/53/query?where=1%3D1&outFields=*&f=json',
    updateCadence: 'source-dependent',
    cameraTypes: ['speed_camera'],
    notes: 'Verified DC speed enforcement dataset; safe to ingest into external_radars.',
    matchingHints: ['dcgis', 'speed detector', 'washington dc'],
  },
  {
    key: 'gov_dc_cctv',
    label: 'DC Traffic Cameras (CCTV)',
    provider: 'government_open_data',
    region: 'Washington, DC',
    countryCodes: ['US'],
    status: 'active',
    ingestMode: 'api',
    alertPolicy: 'map_only',
    endpointUrl: 'https://opendata.dc.gov/datasets/traffic-camera',
    updateCadence: 'source-dependent',
    cameraTypes: ['traffic_enforcement'],
    notes: 'Traffic operations CCTV feed. Keep out of driver alerts.',
    matchingHints: ['dc cctv', 'traffic camera', 'camera:type=cctv'],
  },
  {
    key: 'gov_ca_san_francisco_speed',
    label: 'San Francisco Speed Cameras',
    provider: 'government_open_data',
    region: 'San Francisco',
    countryCodes: ['US'],
    status: 'draft',
    ingestMode: 'manual',
    alertPolicy: 'driver_alert',
    updateCadence: 'snapshot',
    cameraTypes: ['speed_camera'],
    notes: 'Candidate deduped speed-camera dataset derived from saved state export.',
    matchingHints: ['san francisco speed', 'saveddata', 'speed camera'],
  },
  {
    key: 'gov_ca_san_francisco_traffic',
    label: 'San Francisco Traffic Cameras',
    provider: 'government_open_data',
    region: 'San Francisco',
    countryCodes: ['US'],
    status: 'draft',
    ingestMode: 'manual',
    alertPolicy: 'map_only',
    updateCadence: 'snapshot',
    cameraTypes: ['traffic_enforcement'],
    notes: 'Traffic-camera snapshot from the complete US export. Keep map-only.',
    matchingHints: ['san francisco traffic cameras', 'gov_api', 'saveddata'],
  },
  {
    key: 'gov_md_speed_cameras',
    label: 'Maryland Speed Cameras',
    provider: 'government_open_data',
    region: 'Maryland',
    countryCodes: ['US'],
    status: 'draft',
    ingestMode: 'api',
    alertPolicy: 'driver_alert',
    endpointUrl:
      'https://services.arcgis.com/njFNhDsUCentVYJW/ArcGIS/rest/services/SpeedCameras/FeatureServer/0/query?where=1%3D1&outFields=*&f=json',
    updateCadence: 'source-dependent',
    cameraTypes: ['speed_camera'],
    notes: 'Candidate enforcement dataset; re-validate before bulk import.',
    matchingHints: ['maryland', 'speed camera', 'arcgis'],
  },
  {
    key: 'gov_md_montgomery_speed',
    label: 'Montgomery County Speed Cameras',
    provider: 'government_open_data',
    region: 'Maryland',
    countryCodes: ['US'],
    status: 'draft',
    ingestMode: 'manual',
    alertPolicy: 'driver_alert',
    updateCadence: 'snapshot',
    cameraTypes: ['speed_camera'],
    notes: 'Candidate deduped Montgomery County speed-camera dataset from saved export.',
    matchingHints: ['montgomery county', 'speed cameras', 'saveddata'],
  },
  {
    key: 'gov_il_chicago_speed',
    label: 'Chicago Speed Camera Violations',
    provider: 'government_open_data',
    region: 'Chicago',
    countryCodes: ['US'],
    status: 'draft',
    ingestMode: 'manual',
    alertPolicy: 'driver_alert',
    endpointUrl:
      'https://data.cityofchicago.org/resource/hhkd-xvj4.json?$limit=100000&$group=intersection,latitude,longitude&$select=intersection,latitude,longitude',
    updateCadence: 'daily',
    cameraTypes: ['speed_camera'],
    notes: 'Candidate deduped camera points derived from the Chicago violations export.',
    matchingHints: ['chicago', 'speed camera violations', 'socrata', 'saveddata'],
  },
  {
    key: 'gov_il_chicago_red_light',
    label: 'Chicago Red Light Camera Violations',
    provider: 'government_open_data',
    region: 'Chicago',
    countryCodes: ['US'],
    status: 'draft',
    ingestMode: 'manual',
    alertPolicy: 'driver_alert',
    endpointUrl: 'https://data.cityofchicago.org/Transportation/Red-Light-Camera-Violations/spqx-js37',
    updateCadence: 'daily',
    cameraTypes: ['red_light'],
    notes: 'Candidate deduped red-light camera points derived from the Chicago violations export.',
    matchingHints: ['chicago', 'red light camera', 'violations', 'saveddata'],
  },
  {
    key: 'gov_wa_wsdot_cctv',
    label: 'WSDOT Traffic Cameras',
    provider: 'government_open_data',
    region: 'Washington',
    countryCodes: ['US'],
    status: 'draft',
    ingestMode: 'api',
    alertPolicy: 'map_only',
    endpointUrl: 'https://www.wsdot.wa.gov/Traffic/api/Cameras/Cameras.json',
    updateCadence: 'real-time',
    cameraTypes: ['traffic_enforcement'],
    notes: 'Traffic ops CCTV feed, not a speed/red-light enforcement source.',
    matchingHints: ['wsdot', 'camera', 'cctv'],
  },
];

const RULES_BY_KEY = new Map(
  EXTERNAL_CAMERA_SOURCE_RULES.map((rule) => [rule.key.toLowerCase(), rule])
);

export const getExternalCameraSourceRule = (sourceKey?: string | null) => {
  if (!sourceKey) return undefined;
  return RULES_BY_KEY.get(String(sourceKey).trim().toLowerCase());
};
