extend type Query {
  """
  ✨ Look up a single `Interest` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  interest(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Interest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Interest_FirstRow
  ): Interest @fdc_generated(from: "Interest", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Like` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  like(
    """
    The key used to identify the object.
    """
    key: Like_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Like_FirstRow
  ): Like @fdc_generated(from: "Like", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Match` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  match(
    """
    The key used to identify the object.
    """
    key: Match_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Match_FirstRow
  ): Match @fdc_generated(from: "Match", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Message` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  message(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Message_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Message_FirstRow
  ): Message @fdc_generated(from: "Message", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UserInterest` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  userInterest(
    """
    The key used to identify the object.
    """
    key: UserInterest_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UserInterest_FirstRow
  ): UserInterest @fdc_generated(from: "UserInterest", purpose: QUERY_SINGLE)
  """
  ✨ List `Interest` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  interests(
    """
    Filter condition to narrow down the query results.
    """
    where: Interest_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Interest_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Interest_Having
  ): [Interest!]! @fdc_generated(from: "Interest", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Like` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  likes(
    """
    Filter condition to narrow down the query results.
    """
    where: Like_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Like_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Like_Having
  ): [Like!]! @fdc_generated(from: "Like", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Match` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  matches(
    """
    Filter condition to narrow down the query results.
    """
    where: Match_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Match_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Match_Having
  ): [Match!]! @fdc_generated(from: "Match", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Message` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  messages(
    """
    Filter condition to narrow down the query results.
    """
    where: Message_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Message_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Message_Having
  ): [Message!]! @fdc_generated(from: "Message", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UserInterest` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  userInterests(
    """
    Filter condition to narrow down the query results.
    """
    where: UserInterest_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UserInterest_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UserInterest_Having
  ): [UserInterest!]! @fdc_generated(from: "UserInterest", purpose: QUERY_MULTIPLE)
}
